const fs = require("fs");
const path = require("path");

module.exports = function patchNextConfig(repoDir) {
  const configPath = path.join(repoDir, "next.config.js");
  const backupPath = path.join(repoDir, ".next.config.hive.bak");

  if (!fs.existsSync(configPath)) {
    return { patched: false, reason: "no next.config.js" };
  }

  // already patched
  const current = fs.readFileSync(configPath, "utf8");
  if (current.includes("HIVE_DEV_BASEPATH")) {
    return { patched: false, reason: "already patched" };
  }

  // backup once
  if (!fs.existsSync(backupPath)) {
    fs.copyFileSync(configPath, backupPath);
  }

  const wrapper = `
/**
 * ⚠️ AUTO-GENERATED BY HIVE DEV MODE
 * Do not commit this file.
 * Original preserved in .next.config.hive.bak
 */

const originalConfig = require("./.next.config.hive.bak");

const basePath = process.env.BASE_PATH || "";

module.exports = {
  ...(typeof originalConfig === "function"
    ? originalConfig()
    : originalConfig),

  basePath,
  assetPrefix: basePath ? basePath + "/" : undefined,
};
`;

  fs.writeFileSync(configPath, wrapper.trim() + "\n", "utf8");

  return { patched: true };
};
